### ISSUE TITLE
[Feature Request] AccessorySetupKit

### ISSUE THREAD

**Issue by OctopusET** [InfiniTimeOrg/InfiniLink#132]
Apple added new way to connect accessories. 

https://developer.apple.com/documentation/accessorysetupkit

https://www.youtube.com/watch?v=z0YDOmkVMmg

**Comment by liamcharger** [comment]
Thanks for bringing this to my attention, I'll look into it!

**Comment by liamcharger** [comment]
Sorry for my delay in following up with you, @OctopusET!

Using AccessorySetupKit requires replacing the existing Bluetooth controller, and I can't do that because it would force me to change the minimum version to iOS 18 (AccessorySetupKit requires iOS 18 or newer). Incrementing the minimum version just for a feature like this would be unwise, and as some users use devices that can only run iOS 15, the app would be unavailable to them. So unless I can find a way to use them interchangeably, I won't be able to implement this.
