### ISSUE TITLE
Configurable URL to export sensor data live

### ISSUE THREAD

**Issue by Utopiah** [InfiniTimeOrg/InfiniLink#75]
Thanks for the great project and kudos for publishing to the App Store.

I would like to use data from the watch, e.g IMU or heart rate, for VR and AR applications, in particular to motivate physical activity during a work day for its health benefit. Currently the application gather the data and displays it.

Could it be possible to provide a URL and then push the data there in a know format, e.g JSON, so that it can be parsed and used? I imagine pushing data from favorites at a specific frequency, e.g 10 times a second that could also be configurable.

**Comment by liamcharger** [comment]
Hey @Utopiah! This is a great idea! I'm going to try implementing this soon!

**Comment by jones139** [comment]
I'm not so sure about pushing it to a remote server because of the latency in the connections, and the need for a lot of infrastructure to make it work.
The approach I am using for live data is to transfer the data to a phone and process it on the phone rather than a remote server.    
I needed to merge in some pull requests that are not in the main Infinitime source to prevent the HRM timing out, and to send the accelerometer data at 25 Hz, but it seems to be working well now I have done that.
